version: 2
jobs:
  build:
    working_directory: ~/wp-calypso
    docker:
      - image: 'circleci/node:$NODE_VERSION-browsers'
        environment:
          NODE_ENV: test
          TARGET: BRANCHES
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-calypso && git checkout origin/${E2E_BRANCH-master}
      - restore_cache:
          keys:
            - v1-packages-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/yarn.lock" }}-{{ checksum "wp-calypso/test/e2e/package.json" }}
            - v1-packages-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/yarn.lock" }}
            - v1-packages-{{ checksum "wp-calypso/.nvmrc" }}
            - v1-packages
      - run: |
          cd wp-calypso/test/e2e &&
          CHROMEDRIVER_VERSION=$(<.chromedriver_version) yarn --frozen-lockfile
      - save_cache:
          key: v1-packages-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/yarn.lock" }}-{{ checksum "wp-calypso/test/e2e/package.json" }}
          paths:
            - ~/.cache/yarn
      - run: if [ "$LIVEBRANCHES" = true ]; then ./wait-for-running-branch.sh; fi
      - run: cd wp-calypso/test/e2e && yarn run decryptconfig
      - run: sudo chmod +x wp-calypso/test/e2e/node_modules/.bin/magellan
      - run: echo running test command "./run.sh -R ${testFlag--C} $RUN_ARGS"
      - run: cd wp-calypso/test/e2e && ./run.sh -R ${testFlag--C} $RUN_ARGS
      - store_test_results:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/screenshots/
      - run:
          name: Notify webhook of failed build
          when: on_fail
          command: ./wp-calypso/test/e2e/scripts/notify-webhook.sh failed
      - run:
          name: Notify webhook of successful build
          when: on_success
          command: ./wp-calypso/test/e2e/scripts/notify-webhook.sh success
